### ISSUE TITLE
Submission form does not appear

### ISSUE THREAD

**Issue by srondal** [WAJUG/wajug.github.old.com#6]
It happened to me several times, and also to Said: when clicking the "Remplir ce formulaire" button, the form does not show up. Even reloading the page and retrying does not solve this. Not sure yet if this is a Chrome only issue

**Comment by andypetrella** [comment]
Crap... the only way I can reproduce it is when there is a latency (pretty long, though) when fetching vimeo stuffs.
It freezes all subsequent queries (looks like).

When it happens, could you please not if the page is still loading -- you know the wheel (because it still shows up until the vimeo stuffs aren't not there yet)

**Comment by srondal** [comment]
embedded the form on the new version
